---
deployment:
  tasks:
    - export DEPLOYPATH=/home/sakechostingacm/repositories/SAKEC_ACM12
    - export NODE_ENV=production
    - cd $DEPLOYPATH
    - /bin/npm install --production=false
    - /bin/npm run build
    - echo "Build complete. Now start the Node.js app in cPanel interface."
