---
deployment:
  tasks:
    - export DEPLOYPATH=/home/sakechostingacm/public_html/
    - /usr/bin/npm install
    - /usr/bin/npm run build
    - /bin/cp -R dist/* $DEPLOYPATH
    - /bin/cp -R api $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
