-- Insert sample team members with all fields
INSERT INTO team_members (
  name, 
  position, 
  bio, 
  image_url, 
  linkedin_url, 
  github_url, 
  email, 
  year, 
  department, 
  achievements, 
  skills, 
  is_executive, 
  display_order,
  personal_quote,
  about_us,
  cv_url
) VALUES
(
  'Arjun Sharma',
  'President',
  'Leading SAKEC ACM with passion for innovation and technology. Experienced in full-stack development and competitive programming.',
  '/team-president-arjun.png',
  'https://linkedin.com/in/arjun-sharma',
  'https://github.com/arjunsharma',
  'arjun@sakec.ac.in',
  'Final Year',
  'Computer Engineering',
  ARRAY['Winner - National Coding Championship 2023', 'Google Summer of Code 2023', 'Published 3 research papers'],
  ARRAY['JavaScript', 'Python', 'React', 'Node.js', 'Leadership'],
  true,
  1,
  'Innovation is the key to unlocking tomorrow''s possibilities.',
  'Passionate about leading teams and driving technological innovation. With 3+ years of experience in software development and project management, I believe in empowering students to reach their full potential through collaborative learning and hands-on experience.',
  'https://example.com/cv/arjun-sharma.pdf'
),
(
  'Priya Patel',
  'Vice President',
  'Passionate about AI/ML and women in tech advocacy. Leading various technical workshops and mentorship programs.',
  '/team-vp-priya.png',
  'https://linkedin.com/in/priya-patel',
  'https://github.com/priyapatel',
  'priya@sakec.ac.in',
  'Third Year',
  'Computer Engineering',
  ARRAY['Best Project Award - TechFest 2023', 'Women in Tech Leadership Award', 'Hackathon Winner - Mumbai Tech Week'],
  ARRAY['Python', 'Machine Learning', 'TensorFlow', 'Data Science', 'Public Speaking'],
  true,
  2,
  'Success is not final, failure is not fatal: it is the courage to continue that counts.',
  'Dedicated to fostering a culture of excellence and innovation in computer science education. Specializing in competitive programming and algorithm design, I mentor students to develop strong problem-solving skills and technical expertise.',
  'https://example.com/cv/priya-patel.pdf'
),
(
  'Rahul Kumar',
  'Technical Lead',
  'Full-stack developer with expertise in modern web technologies. Leads technical workshops and coding bootcamps.',
  '/team-tech-lead-rahul.png',
  'https://linkedin.com/in/rahul-kumar',
  'https://github.com/rahulkumar',
  'rahul@sakec.ac.in',
  'Final Year',
  'Information Technology',
  ARRAY['Microsoft Student Partner', 'Open Source Contributor', '5+ Production Applications'],
  ARRAY['React', 'Node.js', 'MongoDB', 'AWS', 'Docker'],
  true,
  3,
  'The best code is the code that never needs to be written.',
  'Full-stack developer with expertise in modern web technologies and cloud computing. Committed to organizing impactful technical workshops and hackathons that bridge the gap between academic learning and industry practices.',
  'https://example.com/cv/rahul-kumar.pdf'
),
(
  'Sneha Joshi',
  'Secretary',
  'Organizing events and managing communications. Passionate about cybersecurity and ethical hacking.',
  '/team-secretary-sneha.png',
  'https://linkedin.com/in/sneha-joshi',
  'https://github.com/snehajoshi',
  'sneha@sakec.ac.in',
  'Third Year',
  'Computer Engineering',
  ARRAY['Certified Ethical Hacker', 'Event Management Excellence Award', 'Cybersecurity Workshop Organizer'],
  ARRAY['Cybersecurity', 'Python', 'Network Security', 'Event Management', 'Communication'],
  true,
  4,
  'Organization is the foundation of success.',
  'Detail-oriented professional with strong organizational and communication skills. Responsible for maintaining chapter documentation, coordinating meetings, and ensuring smooth communication between all stakeholders.',
  NULL
),
(
  'Amit Singh',
  'Treasurer',
  'Managing finances and budget planning for ACM chapter activities. Experienced in financial management and sponsorship coordination.',
  '/team-treasurer-amit.png',
  'https://linkedin.com/in/amit-singh',
  'https://github.com/amitsingh',
  'amit@sakec.ac.in',
  'Final Year',
  'Information Technology',
  ARRAY['Financial Management Excellence Award', 'Sponsorship Coordinator', 'Budget Planning Expert'],
  ARRAY['Financial Management', 'Excel', 'Budget Planning', 'Sponsorship', 'Analytics'],
  true,
  5,
  'Financial responsibility today builds opportunities for tomorrow.',
  'Experienced in financial management and budget planning. Focused on ensuring transparent financial practices while maximizing resources for chapter activities and member benefits.',
  'https://example.com/cv/amit-singh.pdf'
),
(
  'Kavya Reddy',
  'General Member',
  'Enthusiastic about technology and eager to contribute to the ACM community. Actively participating in workshops and competitions.',
  '/team-member-kavya.png',
  'https://linkedin.com/in/kavya-reddy',
  'https://github.com/kavyareddy',
  'kavya@sakec.ac.in',
  'Second Year',
  'Computer Engineering',
  ARRAY['Best Debut Performance Award', 'Workshop Participant', 'Competition Finalist'],
  ARRAY['Java', 'Data Structures', 'Algorithms', 'Team Collaboration'],
  false,
  10,
  'Learning is a journey, not a destination.',
  'Enthusiastic about technology and eager to contribute to the ACM community. Actively participating in workshops, competitions, and collaborative projects to enhance skills and build meaningful connections.',
  NULL
),
(
  'Vikram Malhotra',
  'General Member',
  'Passionate about open source development and contributing to meaningful projects. Learning new technologies and sharing knowledge.',
  '/team-member-vikram.png',
  'https://linkedin.com/in/vikram-malhotra',
  'https://github.com/vikrammalhotra',
  'vikram@sakec.ac.in',
  'Third Year',
  'Information Technology',
  ARRAY['Open Source Contributor', 'Hackathon Participant', 'Technical Blog Writer'],
  ARRAY['Python', 'Django', 'PostgreSQL', 'Git', 'Technical Writing'],
  false,
  11,
  'Code is poetry in motion.',
  'Passionate about open source development and contributing to meaningful projects. Learning new technologies and sharing knowledge with the community through technical writing and collaborative development.',
  NULL
);
